### ISSUE TITLE
EDR detected

### ISSUE THREAD

**Issue by Jigsaw855** [0xHossam/Killer#7]
hi my friend I  have  2 questions about your tools 
1 I tested your tools on crowed strike falcon and it detected  your tools , do you have idea about bypass it ? 
2. I created a payload and copy its export in shellcode-xor.py and get this error "IndentationError: unexpected indent" 
3. how shall I run killer correctly ? please explain me

**Comment by kalinavladd** [comment]
I can't compile that tool too) I have any errors, syntax errors, etc. But authors articles are good)

**Comment by 0xHossam** [comment]
Hey all, the first problem that the EDR detected it that's because every thing will be detected while it's public also you shouldn't upload it to crowed strike falcon because that let another anti viruses detect it more but any way I will put updates every time to still FUD!

@kalinavladd If you can't compile it that's mean that you don't understand c++, use visual studio compiler to compile it!

**Comment by kalinavladd** [comment]
@0xHossam Thanks, I'll try. I'm just learning how to develop malware. In the future, I will try to implement your techniques indicated in your articles on rust. Could you recommend a book or materials (preferably fresh and new) on malware development?
